name: CI with GitHub Actions using Ant and JUnit | © 2024 by Lê Trà

# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

on:
  push:
    branches: [ main ] # Lấy code từ nhánh main nếu có ai push code lên  
  pull_request:
    branches: [ main ] # Lấy code từ nhánh main nếu có ai gửi pull request  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Set up JDK 8.0
        uses: actions/setup-java@v3
        with:
          java-version: '8.0'
          distribution: 'temurin'
        
      - name: Set up Apache Ant
        run: sudo apt-get install ant # Cài đặt Apache Ant nếu chưa có sẵn

      - name: Build project with Ant
        run: ant -noinput -buildfile build.xml # Quá trình build với file build.xml

      - name: Distribute jar-war file
        run: mkdir staging && cp dist/*.jar staging # Tạo thư mục staging và sao chép file build vào đó

      - name: Make hyperlink to jar-war file
        uses: actions/upload-artifact@v1  # Chuyển về version v1 nếu cần
        with:
          name: 1.0-SNAPSHOT.jar
          path: staging
